### ISSUE TITLE
Tìm hiểu chung về các cổng thanh toán thương mại điện tử

### ISSUE THREAD

**Issue by damhung0113** [damhung0113/SE04-Nhom4.1#1]
Giới hạn hai cổng thanh toán chính:
1. VNPAY: thanh toán tiền tệ VND
2. PAYPAL: thanh toán tiền tệ USD

Nội dung cơ bản phải nắm được:
- Mô hình kết nối
- Quy trình thanh toán
- Xử lý đơn hàng
- Sơ đồ tuần tự

***
**Phân công công việc: VNP(@quockhanhng , @linhnguyen99hn ) , PAYPAL(@damhung0113 , @nguyenhonglinh )** 
**Quá trình tìm hiểu, thảo luận đều viết vào comment dưới issue này. sẽ có một issue tổng hợp, chọn lọc kết quả.**
*** 

***Input***: Tìm hiểu tài liệu
***Output***: Những nội dung cần nắm được của cổng thanh toán

**Comment by quockhanhng** [comment]
Các nội dung mình tìm hiểu được về cổng thanh toán VNPAY như sau:

**Comment by quockhanhng** [comment]
*Mô hình kết nối*
Website thương mại điện tử (TMĐT) kết nối với cổng thanh toán VnPayment (VNPAY) qua giao thức HTTP Redirect (ssl, checksum)

**Comment by quockhanhng** [comment]
**Quy trình thanh toán**
1. Khách hàng vào website TMĐT để mua hàng và chọn Thanh toán trực tuyến qua VNPAY
2. Website TMĐT gửi thông tin thanh toán của khách hàng sang VNPAY dưới dạng mở cửa sổ popup iframe
3. Khách hàng nhập thông tin xác thực tài khoản Ngân hàng tại VNPAY
4. Khách hàng nhận hàng thanh toán đơn hàng xong, VNPAY sẽ gửi thông báo kết quả thực hiện giao dịch cho Website TMĐT và chuyển Khách hàng tới trang thông báo kết quả giao dịch.

**Comment by quockhanhng** [comment]
**Xử lý đơn hàng**
Căn cứ vào kết quả thực hiện giao dịch mua hàng của khách hàng, đối tác TMĐT (người bán hàng, chủ sở hữu của website TMĐT) sẽ xử lý đơn hàng căn cứ theo kết quả thực hiện giao dịch:
* **Giao dịch thành công**: Đối tác TMĐT tiến hành giao hàng hoặc cung cấp dịch vụ cho khách hàng theo đúng yêu cầu của đơn hàng
* **Giao dịch thành công tại VNPAY nhưng Hết hàng/Không cung cấp được dịch vụ cho khách hàng**: Đối tác TMĐT sẽ lựa chọn việc cung cấp hàng hóa, dịch vụ theo yêu cầu của khách hàng hoặc đăng nhập vào hệ thông quản lý để hoàn tiền cho khách hàng.
* **Giao dịch không thành công**: Căn cứ vào mã lỗi trả về của VNPAY, website TMĐT sẽ hiển thị thông báo lỗi cho khách hàng biết

**Comment by quockhanhng** [comment]
**Sơ đồ tuần tự**
**Bước 1**: Khách hàng vào website TMĐT thực hiện mua hàng và chọn Thanh toán qua VNPAY
**Bước 2**: Website merchant gửi thông tin thanh toàn của khác hàng sang VNPAY 
**Bước 3**: Khách hàng nhập thông tin xác thực thẻ thanh toán tại VNPAY. 
Thông qua kết nối riêng giữa VNPAY và Ngân hàng, VNPAY sẽ gửi yêu cầu sang bên Ngân hàng để thực hiện xác thực tài khoản
Xác thực thành công, Ngân hàng sẽ gửi mật khẩu OTP tới khách hàng, VNPAY chuyển khách hàng sang **bước 4**
**Bước 4**: Khách hàng nhập mật khẩu OTP để hoàn tất giao dịch, VNPAY gửi yêu cầu xác thực OTP sang Ngân hàng. 
Xác hực OTP thành công, hệ thống Ngân hàng sẽ tiến hành chuẩn chi cho giao dịch. Kết thúc bước xác thực OTP hệ thống chuyển khách hàng sang **bước 5**
**Bước 5**: VNPAY thông báo kết quả thanh toán Website TMĐT để website TMĐT tiến hành cập nhật giao dịch thanh toán. 
Nếu giao dịch thành công, Merchant tiến hành xử lý đơn hàng

**Comment by damhung0113** [comment]
Các nội dung mình tìm hiểu được về cổng thanh toán PAYPAL:
- Mô hình kết nối
Website thương mại điện tử (TMĐT) kết nối với cổng thanh toán PAYPAL thông qua việc gọi các API của PAYPAL
- Quy trình thanh toán
Là quy trình thanh toán chung của các cổng thanh toán
Vào trang web mua hàng -> chọn thanh toán bằng PAYPAL -> mở cửa sổ điền thông tin cần thiết -> thanh toán
- Xử lý đơn hàng
Xử lý các trường hợp: thành công, thất bại, thành công tại cổng thanh toán nhưng có lỗi phía server, hoặc ngược lại. Đều có API để backup cho những case này. 
- Sơ đồ tuần tự
Flowpay của PAYPAL không có tài liệu chính thống, mình chỉ tìm hiểu thông qua diễn đàn của paypal.com
**Bước 1**: Khách hàng vào website TMĐT thực hiện mua hàng và chọn Thanh toán qua PAYPAL
**Bước 2**: Website merchant gửi thông tin thanh toàn của khác hàng sang PAYPAL
**Bước 3**: Khách hàng nhập thông tin xác thực, và confirm sử dụng PAYPAL để thanh toán
**Bước 3.1**: PAYPAL trực tiếp kiểm tra các validate, rồi gửi về server là thanh toán thỏa mãn các validate. Server nhận RES rồi cập nhận tình trạng đơn hàng là đã thanh toán nhưng chưa thể thông báo trạng thái là thành công hay thất bại.
**Bước 3.2**: PAYPAL làm việc server to server, nghĩa là làm việc với chính server của PAYPAL hay làm việc với một server nào đó để xác nhận thanh toán ở server cuối. Rồi mới gửi RES về server trang web là thanh toán thành công hay thất bại.
**Bước 4**: Trang web sau khi nhận RES ở **bước 3.2** thì update lại trạng thái của giao dịch lần cuối cùng
_NOTE_: Ở bước 3.2 gần như là chỉ mất vài giây để các server giao tiếp với nhau nên gần như việc thanh toán realtime vẫn hoàn toàn ổn định. Hơn nữa về vấn đề bảo mật nên quy trình server to server được bảo mật rẩt kĩ nên việc giả định quy trình bước này là điểu không thể với một trang web tích hợp cổng thanh toán có sẵn.

**Comment by damhung0113** [comment]
@nguyenhonglinh  @linhnguyen99hn 2 bạn có bổ sung gì về tài liệu phần này không nhỉ

**Comment by linhnguyen99hn** [comment]
@damhung0113 về các vấn đề chính trong các nội dung cơ bản cần nắm được thì mình thấy bạn đã nêu khá đầy đủ và chi tiết nên hiện giờ mình chưa có bổ sung gì thêm

**Comment by nguyenhonglinh** [comment]
Sau đây là những tìm hiểu và tham khảo về quá trình thanh toán Paypal:
**Mô hình kết nối**
Paypal liên kết với 1 website TMĐT thông qua việc gọi các API của Paypal trong quá trình thanh toán.
**Quy trình thanh toán**
Khi hoàn tất quá trình chọn sản phẩm vào giỏ hàng, người dùng bắt đầu lựa chọn phương thức thanh toán.
Khi người dùng thanh toán qua Paypal, cần phải đăng nhập vào Paypal, điền đầy đủ thông tin có trong form.
Tiến hành thanh toán, và theo dõi đơn hàng
**Xử lý đơn hàng**
Thành công: Sẽ gửi về 1 notification đã hoàn thành xác nhận thanh toán sản phẩm
Thất bại: Đưa người dùng quay trở lại phần thiết lập thanh toán
**Sơ đồ tuần tự** (mình tham khảo và thấy bạn Đàm Tiến Hùng đã nêu chi tiết)
Bước 1: Khách hàng vào website TMĐT thực hiện mua hàng và chọn Thanh toán qua PAYPAL
Bước 2: Website merchant gửi thông tin thanh toán của khách hàng sang PAYPAL
Bước 3: Khách hàng nhập thông tin xác thực, và confirm sử dụng PAYPAL để thanh toán
Bước 3.1: PAYPAL trực tiếp kiểm tra các validate, rồi gửi về server là thanh toán thỏa mãn các validate. Server nhận RES rồi cập nhận tình trạng đơn hàng là đã thanh toán nhưng chưa thể thông báo trạng thái là thành công hay thất bại.
Bước 3.2: PAYPAL làm việc server to server, nghĩa là làm việc với chính server của PAYPAL hay làm việc với một server nào đó để xác nhận thanh toán ở server cuối. Rồi mới gửi RES về server trang web là thanh toán thành công hay thất bại.
Bước 4: Trang web sau khi nhận RES ở bước 3.2 thì update lại trạng thái của giao dịch lần cuối cùng

**Comment by damhung0113** [comment]
mình thấy phần @quockhanhng về VNP khá đầy đủ, về phần PAYPAL của mình @quockhanhng có tìm hiểu và bổ sung gì không?

**Comment by quockhanhng** [comment]
@damhung0113 Mình thấy phần tìm hiểu của bạn và @nguyenhonglinh khá đầy đủ theo các chỉ tiêu mà nhóm đã đề ra, good job!

**Comment by damhung0113** [comment]
Vậy chúng ta sẽ tổng hợp phần này sang báo cáo word sớm nhất, phần này mình giao cho @nguyenhonglinh đảm nhiểm.

**Comment by nguyenhonglinh** [comment]
oke, vậy mình sẽ đảm nhiệm tổng hợp word lại những phần chúng ta đã tìm hiểu được về VNPAY và Paypal, nếu có gì cần bổ sung, mọi người liên hệ qua group chat để mình thêm vào phía sau

**Comment by damhung0113** [comment]
Vậy mình close issue.

**Comment by nguyenhonglinh** [comment]
lalala
