### ISSUE TITLE
Thảo luận chọn ngôn ngữ và mô hình để lập trình

### ISSUE THREAD

**Issue by damhung0113** [damhung0113/SE04-Nhom4.1#2]
Do bài toàn liên quan đến payment gateway (cổng thanh toán) cho một trang thương mại điện tử. Nên mình đề xuất sử dụng ngôn ngữ **_<ins>Ruby</ins>_**, framework **_<ins>Ruby on rails</ins>_**, mô hình **_<ins>MVC</ins>_** cơ bản để xây dựng trang web giả định cho bài toán của mình.
#### [?] Tại sao mình chọn ngôn ngữ và framework này, vì mình đã từng làm việc và **_<ins>Ruby on rails</ins>_** là framework khá mạnh và được sử dụng rộng rãi để phát triển web.

***Input***: Thảo luận
***Output***: Lựa chọn được ngôn ngữ lập trình và mô hình

**Comment by quockhanhng** [comment]
@damhung0113 mình nghĩ nếu sử dụng `Ruby` và `Ruby on rails` có thể sẽ khó cho các thành viên còn lại trong nhóm vì chưa có kịnh nghiệm

**Comment by damhung0113** [comment]
@quockhanhng ```Ruby``` là ngôn ngữ khá dễ học cú pháp tương đồng ```Python```, framework cũng rất mạnh, hơn nữa tình hỉnh chung của các bạn đều chưa lập trình web bao giờ. Bỏ ra vài giờ đọc tutorial mình nghĩ sẽ ổn và mình sẽ giúp đỡ mọi người trong việc tiếp cận ngôn ngữ này

**Comment by quockhanhng** [comment]
@nguyenhonglinh @linhnguyen99hn các bạn nghĩ sao, có một số ngôn ngữ cũng hỗ trợ framework làm web khá hữu hiệu như `Java`, `PHP`. Ngoài ra mình cũng nên thảo luận về việc chọn DBMS nhỉ @damhung0113

**Comment by damhung0113** [comment]
@quockhanhng mình thấy nên có issue về DBMS, nhưng nếu có thắc mắc thì bạn nên comment vào issue #3 để tránh bị loãng nhé

**Comment by quockhanhng** [comment]
@damhung0113 okay, chờ 2 bạn kia bàn để xem chốt ngôn ngữ ra sao

**Comment by linhnguyen99hn** [comment]
mình thấy nếu Ruby dễ tiếp cận và tương đồng với một số ngôn ngữ đã tiếp xúc trước đấy rồi thì chọn nó khá phù hợp, còn như mình chưa nắm rõ về nó thì sẽ cố gắng tìm hiểu thêm

**Comment by nguyenhonglinh** [comment]
oke, theo như Hùng nói thì mình thấy code Ruby cũng khá phù hợp, mình sẽ tìm hiểu về ngôn ngữ này và báo cáo với các bạn vào ngày mai

**Comment by damhung0113** [comment]
@nguyenhonglinh mình nghĩ nên vừa làm vừa tìm hiểu hợp lý hơn

**Comment by nguyenhonglinh** [comment]
@damhung0113 oke, mình đã nắm được bài tập cần làm trong tuần này rồi, cuối ngày mình sẽ báo cáo lại tiến bộ trong group chat

**Comment by damhung0113** [comment]
vậy mình sẽ chốt ngôn ngữ và mô hình nhé.

**Comment by damhung0113** [comment]
Ngôn ngữ sử dụng: Ruby (Back-end), HTML CSS JS (Font-end)
Framework: Ruby on rails

**Comment by damhung0113** [comment]
Ngôn ngữ sử dụng: Ruby (Back-end), HTML CSS JS (Font-end)
Framework: Ruby on rails
Mô hình: MVC
