### ISSUE TITLE
Thảo luận chung

### ISSUE THREAD

**Issue by damhung0113** [damhung0113/SE04-Nhom4.1#3]
### Issue dùng để thảo luận của tất cả các thành viên trong nhóm ###
Mọi vấn đề cần chưa hiểu hay phân vân hướng giải quyết đều phải comment bên dưới issue này và chờ các thành viên khác trong team approve rồi mới được tạo new issue (trừ các issue cơ bản, cần thiết)

**Comment by damhung0113** [comment]
Các pull request(PR) về chức năng, tính năng, tài liệu đều phải chờ một, hai hoặc tất cả thành viên trong team approve rồi mới được merge vào master (mình lỡ để repo của chúng ta là main). Các bạn đồng ý chứ? @quockhanhng  @nguyenhonglinh  @linhnguyen99hn

**Comment by quockhanhng** [comment]
@damhung0113 đồng ý 👍

**Comment by damhung0113** [comment]
@quockhanhng  @nguyenhonglinh  mình có assign các bạn vào issue, mọi người nhanh chóng hoàn thành nhé

**Comment by damhung0113** [comment]
Sản phẩm của trang web sẽ là sách, mình học theo cách thiết kế và lấy dữ liệu của trang này nhé: http://nobita.vn/

**Comment by damhung0113** [comment]
@quockhanhng @nguyenhonglinh @linhnguyen99hn  mọi người triển khai bản word giúp mình nhé

**Comment by damhung0113** [comment]
Và phần viết readme nữa, phần này mình nên tham khảo mẫu sao cho hợp lý nhất rồi bắt đầu viết nhé

**Comment by linhnguyen99hn** [comment]
Oke

**Comment by damhung0113** [comment]
các chức năng mọi người phải viết đầy đủ cho 4 tác nhân (khách, người mua, người bán, người quản lý):
- Đăng nhập, đăng ký, đăng xuất (4 tác nhân như nhau)
- Chức năng danh mục: xem các danh mục, riêng admin có quyền thêm sửa xóa danh mục
- Chức năng sản phẩm: xem các sản phẩm, người mua có thể thêm sản phẩm, sửa xóa các sản phẩm của mình. Riêng admin có toàn quyền xóa, sửa (admin không thêm)
- Chức năng giỏ hàng (yêu cầu đăng nhập): chỉ người mua có chức năng này, thêm sản phẩm vào giỏ, sửa số lượng, xóa sản phẩm
- Chức năng thanh toán (yêu cầu đăng nhập): chỉ người mua có chức năng này, thanh toán cho giỏ hàng
- Chức năng giao dịch (khi thanh toán xong sẽ tạo 1 giao dịch cho giỏ hàng vừa được thanh toán): Quản lý trạng thái của giao dịch (phần này ai làm thì để mình inbox riêng mình hướng dẫn chi tiết)

**Comment by damhung0113** [comment]
Qúa trình làm project đã hoàn thành, thứ 2 chúng ta đến trường thi cuối kì với 2 nội dung, check repo và vấn đáp lí thuyết. Chúc cả nhóm thi tốt, mình close issue cuối cùng nhé
