### ISSUE TITLE
Các chức năng chính của dự án

### ISSUE THREAD

**Issue by damhung0113** [damhung0113/SE04-Nhom4.1#4]
### Do đề tài xoay quanh việc xây dựng trang web có <ins>_cổng thanh toán giả định_</ins>, từ kết quả của việc tìm hiểu issue #1 . Mọi người thảo luận rồi đưa ra các chức năng cơ bản nhất của trang web.

**Comment by quockhanhng** [comment]
Mình nghĩ một số tính năng cơ bản mà một trang web e-commerce cần phải có là
1. Đăng ký, đăng nhập
2. Xem danh sách sản phẩm theo danh mục
3. Tìm kiếm sản phẩm 
4. Thêm sản phẩm vào giỏ hàng
5. Thanh toán đơn hàng

**Comment by damhung0113** [comment]
@quockhanhng đồng ý đây là những chức năng cơ bản của người mua. chức năng ***Thêm sản phẩm vào giỏ hàng*** nên tách ra thành: ***thêm, chỉnh sửa các sản phẩm trong giỏ***.
Hiện tại thì cứ tập trung làm cho phần người mua, còn thời gian sẽ làm thêm những chức năng cơ bản của người bán và người quản lý trang web

**Comment by damhung0113** [comment]
Những tính năng của dự án mình đã note vào đây, mọi người follow theo. Nếu có gì thắc mắc thì comment vào #3 chúng ta cùng thảo luận. Mình close issue
https://docs.google.com/spreadsheets/d/1j2gTdgS6lqqxkNOZvo1wzxTVKiIZCK092KcHwmskNVA/edit#gid=0
