### ISSUE TITLE
Triển khai viết README

### ISSUE THREAD

**Issue by damhung0113** [damhung0113/SE04-Nhom4.1#43]

**Comment by damhung0113** [comment]
@quockhanhng báo cáo giúp mình tiến độ tuần vừa rồi với?

**Comment by quockhanhng** [comment]
@damhung0113 tuần vừa rồi mình cập nhật README từ các phần báo cáo tuần trước. Sau khi hoàn thiện mình sẽ push lên

**Comment by damhung0113** [comment]
@quockhanhng hôm nay thấy a Nguyên còn bảo thêm là đưa thêm Goals và Objectives vào readme, chúng ta cần thảo luận và bổ sung thêm phần này. Keyword search: Business goals and objectives

**Comment by quockhanhng** [comment]
@damhung0113 oke

**Comment by damhung0113** [comment]
@quockhanhng update giúp mình tiến độ task Goals và Objectives với

**Comment by quockhanhng** [comment]
@damhung0113 thực ra phần goals & objectives mình đã làm ở phần 1. Mục tiêu rồi
không biết bạn có ý kiến bổ sung gì không

**Comment by damhung0113** [comment]
@quockhanhng mình chưa thấy phần Business Objectives ấy, bạn bổ sung thêm là ổn rồi

**Comment by quockhanhng** [comment]
@damhung0113 
```Nắm được cách hoạt động của các cổng thanh toán (VNPAY, PAYPAL)
Nắm được nghiệp vụ ngân hàng, quy trình tạo một Order của cổng thanh toán
Xây dựng một trang thương mại điện tử có chức năng thanh toán qua Payment Gateway```
phần này mình nghĩ đã bao gồm phần đó rồi

**Comment by damhung0113** [comment]
@quockhanhng đây là mục tiêu của người lập trình, không thuộc phạm trù Goals hay Business Objectives của 1 hệ thống

**Comment by damhung0113** [comment]
phần https://github.com/damhung0113/SE04-Nhom4.1#3-ch%E1%BB%A9c-n%C4%83ng nếu nói là Goals thì còn chính xác chứ https://github.com/damhung0113/SE04-Nhom4.1/issues/43#issuecomment-745386576 thì mình không đồng ý

**Comment by damhung0113** [comment]
Sửa file readme đã xong
