### ISSUE TITLE
Triển khai viết file word báo cáo

### ISSUE THREAD

**Issue by damhung0113** [damhung0113/SE04-Nhom4.1#44]

**Comment by damhung0113** [comment]
@quockhanhng report ở đây nhé

**Comment by quockhanhng** [comment]
@damhung0113  oke

**Comment by quockhanhng** [comment]
Link bài báo cáo đây nhé: https://docs.google.com/document/d/1xkOa6V6XLHHQpGtpAEOLmbXr8mVJeLFsSP6PCzUkLE4

**Comment by damhung0113** [comment]
@quockhanhng báo cáo giúp mình tiến độ tuần vừa rồi với?

**Comment by quockhanhng** [comment]
@quockhanhng tuần vừa rồi, mình và các bạn @nguyenhonglinh, @linhnguyen99hn bổ sung báo cáo phần biểu đồ use-case, biểu đồ trình tự, mô hình thực thể liên kết, đặc thù các cổng thanh toán

**Comment by damhung0113** [comment]
@quockhanhng mọi người đọc kĩ một chút về phần cổng thanh toán PAYPAL và VNP nhé, cả nhóm đều phải hiểu chứ không phải ai tìm hiểu phần nào hiểu phần đó đâu nhé

**Comment by damhung0113** [comment]
Nội dung phân công:
@linhnguyen99hn Phần I. ĐẶC TẢ YÊU CẦU  và II. XÁC ĐỊNH CÁC TÁC NH N VÀ CA SỬ DỤNG (USE CASE)
@quockhanhng Mô tả chung phần III. PHÂN TÍCH, THIẾT KẾ CÁC CHỨC NĂNG CỦA HỆ THỐNG, IV. ĐẶC TẢ CƠ SỞ DỮ LIỆU, và V. ĐẶC THÙ CỔNG THANH TOÁN ĐIỆN TỬ cổng VNP
@nguyenhonglinh Các sơ đồ phần III. PHÂN TÍCH, THIẾT KẾ CÁC CHỨC NĂNG CỦA HỆ THỐNG
@damhung0113  V. ĐẶC THÙ CỔNG THANH TOÁN ĐIỆN TỬ cổng PAYPAL

**Comment by nguyenhonglinh** [comment]
Đã hoàn thành 
1. phần II. Xác định các tác nhận và use case
2. Vẽ biểu đồ use case của
- Nhóm chức năng với tài khoản
- Chức năng thêm sửa xoá danh mục
- Chức năng thêm sửa xoá sản phẩm 
- Xem chi tiết thông tin sản phẩm
- Chức năng với giỏ hàng
- Thanh toán giỏ hàng
- Quản lý giao dịch
3. Vẽ biểu đồ trình tự 
- Nhóm chức năng với tài khoản
- Chức năng thêm sửa xoá danh mục
- Chức năng thêm sửa xoá sản phẩm 
- Xem chi tiết thông tin sản phẩm
- Chức năng với giỏ hàng
- Thanh toán giỏ hàng
- Quản lý giao dịch
=> Hoàn thành phần II và phần III

**Comment by damhung0113** [comment]
@nguyenhonglinh đang bị thiếu phần 1. Mô hình thực thể - liên kết, bạn update giúp mình

**Comment by nguyenhonglinh** [comment]
@damhung0113 Mình vừa cập nhật phần mô hình thực thể trong file báo cáo, bạn check giúp mình xem đã ổn chưa nhé.

**Comment by damhung0113** [comment]
@nguyenhonglinh triển khai giúp mình luôn phần slide nhé

**Comment by damhung0113** [comment]
Mình close issue vì phần word đã ổn, nếu có vấn đề sẽ reopen
