### ISSUE TITLE
Thảo luận lựa chọn DBMS cho dự án

### ISSUE THREAD

**Issue by damhung0113** [damhung0113/SE04-Nhom4.1#5]
Do dự án cơ bản là một trang web, nên phải làm việc dữ liệu được lưu trữ. Vậy nên cần lựa chọn một DBMS hợp lý.

***Input***: Thảo luận
***Output***: Chọn ra được DBMS cho dự án

**Comment by damhung0113** [comment]
Do trang web chỉ là trang web mua bán hàng cơ bản, có tích hợp cổng thanh toán. Nên mình nghĩ lựa chọn hệ quản trị cơ sở dữ liệu là MySQL. Tất cả thành viên đều đã từng sử dụng, và nếu có thể phát triển thêm mình nghĩ sẽ sử dụng song song firebase để làm các chức năng real-time, hiện tại thì chưa cần thiết.

**Comment by damhung0113** [comment]
@quockhanhng  @nguyenhonglinh @linhnguyen99hn các bạn thảo luận về vấn đề này

**Comment by nguyenhonglinh** [comment]
oke bạn, mình sẽ hoàn thành trong thời gian muộn nhất là ngày mai

**Comment by nguyenhonglinh** [comment]
không biết bao giờ báo cáo giữa kỳ nhỉ?

**Comment by damhung0113** [comment]
@nguyenhonglinh  tập trung vào issue lựa chọn DBMS

**Comment by quockhanhng** [comment]
@damhung0113 bạn đã có kinh nghiệm làm với `Ruby` và `Ruby on Rails`, không biết dùng nó kết nối tới `MySQL` có phức tạp lắm không?

**Comment by damhung0113** [comment]
@quockhanhng nó sử dụng kĩ thuật ORM (Object Relational Mapping) nên không phải viết truy vấn đơn giản, dễ dàng và thuận tiện, đối với truy vấn khó thì việc học MySQL của mọi người sẽ được phát huy

**Comment by nguyenhonglinh** [comment]
theo mình tìm hiểu ORM là một kỹ thuật lập trình để chuyển đổi dữ liệu giữa các cơ sở dữ liệu quan hệ và các ngôn ngữ lập trình hướng đối tượng. Cho phép đối tượng truy cập mã nghiệp vụ thay vì bảng DB.

**Comment by damhung0113** [comment]
@nguyenhonglinh sáng nay học mà bạn :cry:

**Comment by linhnguyen99hn** [comment]
@damhung0113 nếu sử dụng ORM có tương đồng nhiều vs các ngôn ngữ khác khi kết nối với mysql ko

**Comment by damhung0113** [comment]
@linhnguyen99hn mỗi ngôn ngữ có cách mapping riêng, nhưng ruby thì cú pháp khá giống python vì đều là dynamic language

**Comment by damhung0113** [comment]
vậy mình chốt sử dụng MySQL nhé, về cách sử dụng ORM thì có lẽ vào project mọi người sẽ hiểu nhanh thôi

**Comment by nguyenhonglinh** [comment]
@damhung0113  Oke bạn, vậy sử dụng MySQL cũng được, vì đây là môn học mình đã được học từ năm 2 rồi, có thể mình sẽ dễ dàng trong việc làm đự án hơn, không biết các bạn còn lại thì sao nhỉ?

**Comment by nguyenhonglinh** [comment]
@quockhanhng @linhnguyen99hn  2 bạn muốn được làm theo gì?

**Comment by linhnguyen99hn** [comment]
Oke vậy chốt Mysql nhé

**Comment by nguyenhonglinh** [comment]
oke, có gì mai lên trường gặp nhau, chúng ta sẽ nói rõ hơn về những gì cần làm trong hệ cơ sở MySQL

**Comment by damhung0113** [comment]
Quyết định chọn mysql, vậy mình close issue nhé
