### ISSUE TITLE
Thiết kế database

### ISSUE THREAD

**Issue by damhung0113** [damhung0113/SE04-Nhom4.1#6]
Dưới đây mô hình ER mình thiết kế với nội dung đề tài về trang web bán hàng cơ bản có tích hợp cổng thanh toán, mọi người cho ý kiến nhận xét. @quockhanhng  @nguyenhonglinh  @linhnguyen99hn 

Cơ bản về nội dung như sau:
- Bảng User thể hiện cho đối tượng người mua hoặc người bán thể hiện qua trường role, có các thông tin cơ bản của một user.
- Bảng Product thể hiện cho đối tượng  sản phẩm được bán bởi người bán, thuộc về một danh mục, có các thông tin cơ bản của một sản phẩm.
- Bảng Cart thể hiện cho đối tượng giỏ hàng, có trạng thái giỏ hàng, tổng tiền, và các sản phẩm trong giỏ.
- Bảng Cart_item thể hiện cho đối tượng các sản phẩm có trong giỏ hàng, lưu trữ các thông tin của sản phẩm tại thời điểm mua hàng để tránh bị sai dữ liệu ở thời điểm khác nhau.
- Bảng Pg_transaction thể hiện cho đối tượng giao dịch của người mua và người bán, hay có thể gọi là đơn hàng. Bảng này lưu trữ thông tin về tổng tiền phải trả, cách thức thanh toán, các thông tin thanh toán...
- Bảng Category thể hiện cho đối tượng danh mục của sản phẩm.

![image](https://user-images.githubusercontent.com/44402218/97256012-8e596c80-1844-11eb-9972-384214fad133.png)

**Comment by quockhanhng** [comment]
@damhung0113 bạn cho mình hỏi trường `price` ở bảng `cart_items` có cần thiết không?

**Comment by damhung0113** [comment]
cần thiết chứ, nó lưu lại giá tại thời điểm mua, vì người bán có thể thay đổi giá của sản phẩm
