### ISSUE TITLE
Cài đặt môi trường

### ISSUE THREAD

**Issue by damhung0113** [damhung0113/SE04-Nhom4.1#7]
Issue tạo ra để trợ giúp các thành viên trong team cài môi trường cho dự án
Link step by step cài đặt Ruby và Ruby on rails: https://gorails.com/setup
### Lưu ý:
- Nên sử dụng **UbuntuOS** hoặc **MacOS**
- **Window** hiện tại không thích hợp để sử dụng Ruby on rails.

**Comment by damhung0113** [comment]
@quockhanhng @nguyenhonglinh @linhnguyen99hn các bạn cài đặt thành công hoặc cần giúp đỡ thì comment dưới issue này nhé

**Comment by damhung0113** [comment]
Version mình đang sử dụng:
- Ruby: 2.7.1
- Rails: 6.0.3.4
- MySQL: 8.0.21

**Comment by linhnguyen99hn** [comment]
Như ở trên bạn nói thì window không hỗ trợ à bạn ?

**Comment by damhung0113** [comment]
@linhnguyen99hn search google thì có nhưng mà mình đã từng thử thì gặp tương đối nhiều lỗi, nên sử dựng Ubuntu hoặc Mac sẽ ổn định hơn

**Comment by linhnguyen99hn** [comment]
@damhung0113 oke bạn

**Comment by quockhanhng** [comment]
@damhung0113 oke bạn, mình đã cài đặt thành công môi trường rồi

**Comment by nguyenhonglinh** [comment]
@damhung0113  oke ban, vay minh se cai dat version nay

**Comment by damhung0113** [comment]
@nguyenhonglinh @linhnguyen99hn đã cài thành công môi trường chưa vậy?

**Comment by damhung0113** [comment]
@quockhanhng pull repo về chạy thử xem nào

**Comment by linhnguyen99hn** [comment]
@damhung0113 mình tìm bản 2.7.1 thì ko thấy toàn thấy bản 2.7.2

**Comment by damhung0113** [comment]
@linhnguyen99hn ruby version thì không cần quan tâm lắm đâu 2.7, rails 6 là được rồi

**Comment by linhnguyen99hn** [comment]
@damhung0113 oke bạn

**Comment by nguyenhonglinh** [comment]
mình gặp phải vấn đề về phiên bản macOS, nó bắt cập nhật lên phiên bản mới nhất mới có thể cài đặt được rails, mình sẽ cố gắng cài đặt sớm

**Comment by damhung0113** [comment]
@quockhanhng @nguyenhonglinh @linhnguyen99hn nếu các bạn vẫn gặp khó khăn, mình sẽ support trực tiếp sau giờ học ngày mai (nếu có thể sup).

**Comment by nguyenhonglinh** [comment]
oke, nhờ có sự hướng dẫn của bạn Hùng, mình đã cài đặt được môi trường Ruby vài rails rồi, cảm ơn các bạn

**Comment by damhung0113** [comment]
@linhnguyen99hn mình cần bạn report về tình trạng hiện giờ, máy đã có môi trường chưa và chưa thấy thông báo gì cả

**Comment by linhnguyen99hn** [comment]
@damhung0113 hiện tại mình mới cài được rubby, chưa cài được rails do lỗi, mình đang tìm cách khắc phục

**Comment by damhung0113** [comment]
Close vì không thấy phản hồi và báo cáo. Thành viên còn lại OK
